<?php

global $SDK_VER;
global $UCLOUD_PROXY_SUFFIX;
global $UCLOUD_PUBLIC_KEY;
global $UCLOUD_PRIVATE_KEY;
global $CALL_BACK_URL;
global $CALL_BACK_BODY;

$SDK_VER = "1.0.6";

$UCLOUD_PROXY_SUFFIX = '.cn-bj.ufileos.com';

//$UCLOUD_PUBLIC_KEY = '';
//$UCLOUD_PRIVATE_KEY = '';
$UCLOUD_PUBLIC_KEY = '';
$UCLOUD_PRIVATE_KEY = '';
$CALL_BACK_URL = "";
$CALL_BACK_BODY = "";
